### PR TITLE
Feat/ezpay invoice function

### PR DESCRIPTION
**Pull request by inkybr**
@hcchien @nickhsine I am keen to use the function to trigger EZPay and leave the detail of the payload to the desired caller. The function will be for subscription invoice only. Please kindly share your thoughts. Thanks.

# Function and functionality

The function is bound to be triggered by [POST HTTPS request](https://cloud.google.com/functions/docs/concepts/events-triggers#triggers), and in production environment it will not be a public function. Requests are authenticated by IAM.

The client may call to function to
1. 開立發票

The POST payload MUST be s JSON object which follows the spec of EZPay's **PostData_內含欄位**, where **參數名稱** are the keys in the JSON object.

There's a restriction though. Due to the current implementation, `RespondType` must be `JSON`. It's a bug and it will be fixed in the future.

The function will honor the payload of the trigger data and pass it to EZPay. Because the response data needs to be processed by the caller, the response from function will be identical to response of EZPay in cases other then `500` `400`, and `403`.

Issue:
1. ~~CORS preflight handler is missing~~ (It's not a public function, so CORS preflight handler is not needed)
2. ~~HTTP Method filter is missing~~ fixed
2. `RespondType` must be `JSON`

Doc:
ezPay invoice spec 1.2.1: [EZP_INVI_1_2_1.pdf](https://github.com/mirror-media/payment-go/files/7215225/EZP_INVI_1_2_1.pdf)

Usage:
It can be triggered in different ways:
1. A post request can be sent to `https://asia-east1-mirrormedia-1470651750304.cloudfunctions.net/weekly-subscribtion-ezpay-invoice-issuer` with GCP Identity token as its `Bearer Token`, and the identity must have permission to invoke cloud functions.
2. Use `gcloud`: `gcloud functions call weekly-subscribtion-ezpay-invoice-issuer --data '{"name":"Keyboard Cat"}'` which is convenient.
3. Use GCP Cloud Function Client SDK: https://cloud.google.com/nodejs/docs/reference/functions/latest

```json
{
	"RespondType":"JSON",
	"Version": "1.5",
	"TimeStamp": "1632665865",
	"MerchantOrderNo": "M21092600001_01",
	"Status": "1",
	"Category": "B2C",
	"BuyerName": "Name",
	"BuyerEmail": "i.am@e.mail",
	"CarrierType": "0",
	"CarrierNum": "/A123456",
	"TaxType": "1",
	"TaxRate": 5,
	"Amt": 100,
	"TaxAmt": 5,
	"TotalAmt": 105,
	"ItemName": "商品名稱",
	"ItemCount": 1,
	"ItemUnit": "期",
	"ItemPrice": 105,
	"ItemAmt": 105,
	"PrintFlag": "N"
}
```

You may test the deployment at https://console.cloud.google.com/functions/details/asia-east1/weekly-subscribtion-ezpay-invoice-issuer?project=mirrormedia-1470651750304&tab=testing

### CODE REVIEW

**Comment by hcchien** [comment]
LGTM

**Comment by nickhsine** [comment]
這之後會是部署在 cloud function 上嗎？

**Comment by inkybr** [comment]
@nickhsine 對

**Comment by nickhsine** [comment]
好奇 cloud function 的部署方便嗎？
我之前用的時候，它是透過 source code 去部署，剛剛去試了一下，好像還是一樣？

**Comment by hcchien** [comment]
> 好奇 cloud function 的部署方便嗎？
> 我之前用的時候，它是透過 source code 去部署，剛剛去試了一下，好像還是一樣？

是不是 cloud run 比較方便？

**Comment by hcchien** [comment]
> > 好奇 cloud function 的部署方便嗎？
> > 我之前用的時候，它是透過 source code 去部署，剛剛去試了一下，好像還是一樣？
> 
> 是不是 cloud run 比較方便？

cloud function 要用 cloud source 放 code
cloud run 可以直接用 github 無痛完成 CI/CD

**Comment by inkybr** [comment]
cloud function 可以用 github
https://cloud.google.com/functions/docs/deploying/repo

**Comment by inkybr** [comment]
我沒有要寫成一個完成的服務啦，寫 function 會比較方便。

**Comment by hcchien** [comment]
> cloud function 可以用 github
> https://cloud.google.com/functions/docs/deploying/repo

喔喔，我是看 web ui
所以 commit 也會 trigger 更新嗎

**Comment by inkybr** [comment]
要透過 cloud build 來 trigger 更新，文件是建議在 cloud build 裡面一起跑 test 再更新。

**Comment by hcchien** [comment]
所以 subscriber 發票資料送到 espy 成功之後，怎麼 trigger 去更新資料庫？

**Comment by inkybr** [comment]
目前不是用 PobSub 的 subscriber 方式來，而是用 http 的 endpoint，所以打好 ezpay 的 api 之後，會把 ezpay 的 response 回傳給 client，讓 client 做處理。

**Comment by inkybr** [comment]
這個 function 目前的設計只有單純開發票而已。

**Comment by inkybr** [comment]
主要是因為希望以後開發票的處理都可以透過這個 function，所以是做成 product-agnostic，裡面沒有會員或是 `Israfel` 的邏輯在裡面，而 client 可以自己決定使用的 api 版本、內容、跟發票開完之後決定要怎麼處理。

**Comment by inkybr** [comment]
我部署了一支到 GCP 上了，可以到這個網頁上測試： https://console.cloud.google.com/functions/details/asia-east1/weekly-subscribtion-ezpay-invoice-issuer?project=mirrormedia-1470651750304&tab=testing

目前因為設定的關係，應該會拿到 `400` `invoice creation error: create invoice error:取得商店申請資格失敗`
 的回應

**Comment by nickhsine** [comment]
LGTM

**Comment by nickhsine** [comment]
@bcgodev 可以請你提供一下此 API 的 response format 嗎？

**Comment by hcchien** [comment]
> @bcgodev 可以請你提供一下此 API 的 response format 嗎？

{"Message":"發票開立成功","Result":"{\"CheckCode\":\"82F2202D05C83EF69656F15377555F364DC0E86DE2BD8B506F85709EA5BD768A\",\"MerchantID\":\"33901549\",\"MerchantOrderNo\":\"M21092600001_01\",\"InvoiceNumber\":\"AA00000000\",\"TotalAmt\":105,\"InvoiceTransNo\":\"21092718473292763\",\"RandomNum\":\"2559\",\"CreateTime\":\"2021-09-27 18:47:32\"}","Status":"SUCCESS"}

**Comment by nickhsine** [comment]
> > @bcgodev 可以請你提供一下此 API 的 response format 嗎？
> 
> {"Message":"發票開立成功","Result":"{"CheckCode":"82F2202D05C83EF69656F15377555F364DC0E86DE2BD8B506F85709EA5BD768A","MerchantID":"33901549","MerchantOrderNo":"M21092600001_01","InvoiceNumber":"AA00000000","TotalAmt":105,"InvoiceTransNo":"21092718473292763","RandomNum":"2559","CreateTime":"2021-09-27 18:47:32"}","Status":"SUCCESS"}

成功的 status code 是 200?
錯誤的話會有哪幾種 status code 呢？
錯誤的 response format 會是？

**Comment by hcchien** [comment]
> > > @bcgodev 可以請你提供一下此 API 的 response format 嗎？
> > 
> > 
> > {"Message":"發票開立成功","Result":"{"CheckCode":"82F2202D05C83EF69656F15377555F364DC0E86DE2BD8B506F85709EA5BD768A","MerchantID":"33901549","MerchantOrderNo":"M21092600001_01","InvoiceNumber":"AA00000000","TotalAmt":105,"InvoiceTransNo":"21092718473292763","RandomNum":"2559","CreateTime":"2021-09-27 18:47:32"}","Status":"SUCCESS"}
> 
> 成功的 status code 是 200? 錯誤的話會有哪幾種 status code 呢？ 錯誤的 response format 會是？

invoice creation error: create invoice error:該筆自訂單號已重覆開立發票，請確認

**Comment by inkybr** [comment]
> > > @bcgodev 可以請你提供一下此 API 的 response format 嗎？
> > 
> > 
> > {"Message":"發票開立成功","Result":"{"CheckCode":"82F2202D05C83EF69656F15377555F364DC0E86DE2BD8B506F85709EA5BD768A","MerchantID":"33901549","MerchantOrderNo":"M21092600001_01","InvoiceNumber":"AA00000000","TotalAmt":105,"InvoiceTransNo":"21092718473292763","RandomNum":"2559","CreateTime":"2021-09-27 18:47:32"}","Status":"SUCCESS"}
> 
> 成功的 status code 是 200? 錯誤的話會有哪幾種 status code 呢？ 錯誤的 response format 會是？

500 跟 403 會是 function 回的錯誤代碼，body 是空白的。

200 是 ezpay 會的 http code，內容是 ezpay 的回應，裡面應該要是 JSON 才對，但不太清楚為什麼目前會拿到字串的回應。

**Comment by inkybr** [comment]
@nickhsine 剛剛不好意思說錯了，錯誤代碼總共會有 500、400、403。
而 200 則是 ezpay 的回應沒錯。

**Comment by inkybr** [comment]
我要先 merge 這個 PR，然後修 `RespondType` must be `JSON` 這個問題囉。

**Pull request merged**
